# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea217809416b763540e496c47e50975d1cf7d6f115c451b2b8f2664fb545b7e1660768684fb6ae1c9d0f3139583541095e6577f2156f5c8857fd5b4bc2b390c

test:
  secret_key_base: cd4f5cb0a2018aa8facbaad341c44a30fe6dbf1620e7d1a9aecacfdf2325942eb672be53e6d15c7e6e027d65a3795afdecf844bc9f01d3f710547fc85b04bf12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
